version: '3'
services:
  retwisj:
    build: .
    ports:
      - '8080:8080'
    links:
      - redis
  retwisj-dev:
    build: .
    command: bash
    ports:
      - '8080:8080'
    links:
      - redis
    working_dir: /home/retwisj
    volumes:
      - '.:/home/retwisj'
  redis:
    image: redis
    expose:
      - '6379'
