version: '3'
services:
  acl-uk:                 
    build: ./acl                          
    links:                                
     - redis-acl-uk:redis2
    expose:                               
     - '8080'                             
     - '8084'                             
     - '9090'                             
    environment:                 
      - ACL_LINKS=acl-us:acl-eu
      - MY_NAME=acl-uk
  redis-acl-uk:           
    image: redis            
    expose:                 
      - '6379'              
  retwisj-uk:                   
    build: ./retwisj         
    ports:                   
      - '8080:8080'  
    links:                   
      - redis-ret-uk:redis 
      - acl-uk:acl         
    environment:                 
      - RET_LINKS=retwisj-us:retwisj-eu
      - MY_NAME=acl-uk
  redis-ret-uk:
    image: redis 
    expose:      
      - '6379'   

  acl-us:                 
    build: ./acl                          
    links:                                
     - redis-acl-us:redis2
    expose:                               
     - '8080'                             
     - '8084'                             
     - '9090'                             
    environment:                 
      - ACL_LINKS=acl-uk:acl-eu
      - MY_NAME=acl-us
  redis-acl-us:           
    image: redis            
    expose:                 
      - '6379'              
  retwisj-us:                   
    build: ./retwisj         
    ports:                   
      - '8081:8080'  
    links:                   
      - redis-ret-us:redis 
      - acl-us:acl         
    environment:                 
      - RET_LINKS=retwisj-uk:retwisj-eu
      - MY_NAME=acl-us
  redis-ret-us:
    image: redis 
    expose:      
      - '6379'   

  acl-eu:                 
    build: ./acl                          
    links:                                
     - redis-acl-eu:redis2
    expose:                               
     - '8080'                             
     - '8084'                             
     - '9090'                             
    environment:                 
      - ACL_LINKS=acl-uk:acl-us
      - MY_NAME=acl-eu
  redis-acl-eu:           
    image: redis            
    expose:                 
      - '6379'              
  retwisj-eu:                   
    build: ./retwisj         
    ports:                   
      - '8082:8080'  
    links:                   
      - redis-ret-eu:redis 
      - acl-eu:acl         
    environment:                 
      - RET_LINKS=retwisj-uk:retwisj-us
      - MY_NAME=acl-eu
  redis-ret-eu:
    image: redis 
    expose:      
      - '6379'   

