version: '3'
services:
  retwisj:
    build: ./retwisj
    ports:
      - '8080:8080'
    links:
      - redis
      - acl
  acl:
    build: ./acl
  
  redis:
    image: redis
    expose:
      - '6379'
