version: '3'
services:
  acl-1:                 
    build: ./acl            
    links:                  
     - redis-acl-1:redis2
    expose:                 
     - '8080'               
     - '8084'               
     - '9090'               
    environment:                 
      - ACL_LINKS=acl-2:acl-3:acl-4
      - MY_NAME=acl-1
  redis-acl-1:           
    image: redis            
    expose:                 
      - '6379'              
  retwisj-1:                   
    build: ./retwisj         
    ports:                   
      - '8080:8080'  
    links:                   
      - redis-ret-1:redis 
      - acl-1:acl         
    environment:                 
      - RET_LINKS=ret-2:ret-3:ret-4
      - MY_NAME=acl-1
  redis-ret-1:
    image: redis 
    expose:      
      - '6379'   

  acl-2:                 
    build: ./acl            
    links:                  
     - redis-acl-2:redis2
    expose:                 
     - '8080'               
     - '8084'               
     - '9090'               
    environment:                 
      - ACL_LINKS=acl-1:acl-3:acl-4
      - MY_NAME=acl-2
  redis-acl-2:           
    image: redis            
    expose:                 
      - '6379'              
  retwisj-2:                   
    build: ./retwisj         
    ports:                   
      - '8081:8080'  
    links:                   
      - redis-ret-2:redis 
      - acl-2:acl         
    environment:                 
      - RET_LINKS=ret-1:ret-3:ret-4
      - MY_NAME=acl-2
  redis-ret-2:
    image: redis 
    expose:      
      - '6379'   

  acl-3:                 
    build: ./acl            
    links:                  
     - redis-acl-3:redis2
    expose:                 
     - '8080'               
     - '8084'               
     - '9090'               
    environment:                 
      - ACL_LINKS=acl-1:acl-2:acl-4
      - MY_NAME=acl-3
  redis-acl-3:           
    image: redis            
    expose:                 
      - '6379'              
  retwisj-3:                   
    build: ./retwisj         
    ports:                   
      - '8082:8080'  
    links:                   
      - redis-ret-3:redis 
      - acl-3:acl         
    environment:                 
      - RET_LINKS=ret-1:ret-2:ret-4
      - MY_NAME=acl-3
  redis-ret-3:
    image: redis 
    expose:      
      - '6379'   

  acl-4:                 
    build: ./acl            
    links:                  
     - redis-acl-4:redis2
    expose:                 
     - '8080'               
     - '8084'               
     - '9090'               
    environment:                 
      - ACL_LINKS=acl-1:acl-2:acl-3
      - MY_NAME=acl-4
  redis-acl-4:           
    image: redis            
    expose:                 
      - '6379'              
  retwisj-4:                   
    build: ./retwisj         
    ports:                   
      - '8083:8080'  
    links:                   
      - redis-ret-4:redis 
      - acl-4:acl         
    environment:                 
      - RET_LINKS=ret-1:ret-2:ret-3
      - MY_NAME=acl-4
  redis-ret-4:
    image: redis 
    expose:      
      - '6379'   


  registry:
    build: ./registry
    expose:
      - '5050'
