version: '3'
services:
  acl-eu:                 
    build: ./acl                          
    links:                                
     - redis-acl-eu:redis2
    expose:                               
     - '8080'                             
     - '8084'                             
     - '9090'                             
    environment:                 
      - ACL_LINKS=acl-us
      - MY_NAME=acl-eu
  redis-acl-eu:           
    image: redis            
    expose:                 
      - '6379'              
  retwisj-eu:                   
    build: ./retwisj         
    ports:                   
      - '8080:8080'  
    links:                   
      - redis-ret-eu:redis 
      - acl-eu:acl         
    environment:                 
      - RET_LINKS=retwisj-us
      - MY_NAME=retwisj-eu
  redis-ret-eu:
    image: redis 
    expose:      
      - '6379'   

  acl-us:                 
    build: ./acl                          
    links:                                
     - redis-acl-us:redis2
    expose:                               
     - '8080'                             
     - '8084'                             
     - '9090'                             
    environment:                 
      - ACL_LINKS=acl-eu
      - MY_NAME=acl-us
  redis-acl-us:           
    image: redis            
    expose:                 
      - '6379'              
  retwisj-us:                   
    build: ./retwisj         
    ports:                   
      - '8081:8080'  
    links:                   
      - redis-ret-us:redis 
      - acl-us:acl         
    environment:                 
      - RET_LINKS=retwisj-eu
      - MY_NAME=retwisj-us
  redis-ret-us:
    image: redis 
    expose:      
      - '6379'   

  sandbox:           
    build: ./sandbox 
    expose:
     - '8080'
    ports: 
     - '1010:8080'
    environment:       
      - RET_LINKS=retwisj-eu:retwisj-us